sitediam/sitediam/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('sports24h/', include('sports24h.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
 urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitediam/sports24h/urls.py
from django.urls import include, path
from . import views

# (. significa que importa views da mesma directoria)
app_name = 'sports24h'

urlpatterns = [
    path("", views.index, name="index"),

    path("posts_index", views.posts_index, name="posts_index"),

    path("products_index", views.products_index, name="products_index"),

    path("register", views.register_user, name="register_user"),

    path("login", views.login_user, name="login_user"),

    path("logout", views.logout_user, name="logout_user"),

    path("forums", views.forums_index, name="forums_index"),

    path("buy_products", views.buy_products, name="buy_products"),

    path("bough_products", views.bough_products, name="bough_products"),

    path('add_review/<int:product_id>/', views.add_review, name='add_review'),

    path("follow_forum", views.follow_forum, name="follow_forum"),

    path("unfollow_forum", views.unfollow_forum, name="unfollow_forum"),

    # create forum
    path("create_forum", views.forum, name="create_forum"),

    path("create_post", views.post, name="create_post"),

    path("delete_post", views.delete_post, name="delete_post"),

    # post/1  - detail
    path("post/<int:post_id>", views.post_detail, name="post_detail"),

    path("add_comment", views.add_comment, name="add_comment"),

    path("create_product", views.product, name="create_product"),

    path("delete_product", views.delete_product, name="delete_product"),

    # product/1  - detail
    path("product/<int:product_id>", views.product_detail, name="product_detail"),

    # add to cart
    path("add_to_cart/<int:product_id>", views.add_to_cart, name="add_to_cart"),

    path("remove_from_cart/<int:product_id>", views.remove_from_cart, name="remove_from_cart"),

    # seller products
    path('seller_products', views.seller_products, name='seller_products'),

    #admin views
    #path("create_country", views., name="create_product"),

    path("create_country", views.country, name="create_country"),

    path("create_size", views.size, name="create_size"),

    path("create_sport", views.sport, name="create_sport"),

    path("create_team", views.team, name="create_team"),

    # user profile
    path("profile", views.profile, name="profile"),

    # upload photo
    path('upload_photo', views.upload_photo, name='upload_photo'),

    # set country
    path('set_country', views.set_country, name='set_country'),

    # set favoriteTeam
    path('set_favoriteTeam', views.set_favoriteTeam, name='set_favoriteTeam'),

    # set favoriteSport
    path('set_favoriteSport', views.set_favoriteSport, name='set_favoriteSport'),
    # reset foto
    path('reset_photo', views.reset_photo, name='reset_photo'),

    # shopping cart
    path('shopping_cart', views.shopping_cart, name='shopping_cart'),

    # send messages
    path('send_message/', views.send_message_html, name='send_message_html'),
    path('send_message/submit/', views.send_message_submit, name='send_message_submit'),

    #receive messages
    path('send_message/', views.inbox, name='receive_message'),

    #sent messages
    path('sent_messages/', views.sent_messages_html, name='sent_messages_html'),

    # like post
    path('like/<int:post_id>', views.like, name='like'),

    # about
    path('about/', views.about_index, name='about_index'),

    path('search_users', views.search_users, name='search_users'),

    path('other_user_profile/<int:user_id>/', views.other_user_profile, name='other_user_profile'),

    path('follow_user', views.follow_user, name='follow_user'),

    path('unfollow_user', views.unfollow_user, name='unfollow_user'),

    path('admin', views.admin, name='admin'),

    path('acess_denied', views.access_denied, name='access_denied'),

    path('delete_account', views.delete_account, name='delete_account'),

    path('api/posts/', views.post_list),
    path('api/posts/<int:pk>', views.post_detail),
    path('api/comments/', views.comment_list),

]

sitediam/sports24h/views.py
from datetime import date
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.core.validators import validate_email
from django.db.models import Subquery, Avg, Q
from django.shortcuts import render, redirect, get_object_or_404
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view

from .models import Message, Product, Size, ShoppingCart, Follows, Comment, Likes, BoughtProducts, SellerProduct, Review,  FollowsForum
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.urls import reverse, reverse_lazy
from .models import Post, Forum, Client, Seller, Country, Team, Sport
from .serializers import PostSerializer, CommentSerializer, UserSerializer, OwnerSerializer

from django.contrib.auth import get_user_model


def seller_check(user):
    return Seller.objects.filter(user=user).exists()


@login_required(login_url=reverse_lazy('sports24h:login_user'))
def index(request):
    user_type = None
    is_seller = False  # Initialize is_seller as False

    if hasattr(request.user, 'client'):
        user_type = 'client'
    elif hasattr(request.user, 'seller'):
        user_type = 'seller'
        is_seller = True

    post_list = Post.objects.order_by('-created_at')
    liked_posts = Post.objects.filter(likes__user=request.user)
    product_list = Product.objects.order_by('-created_at')


    if user_type == 'client':
        User = get_user_model()
        client_user = User.objects.get(client=request.user.client)
        followed_forums = FollowsForum.objects.filter(user=client_user)

        followed_forums_post = []
        for forum in followed_forums:
            forum_posts = Post.objects.filter(forum=forum.forum)
            followed_forums_post += forum_posts
    else:
        User = get_user_model()
        client_user = User.objects.get(seller=request.user.seller)
        followed_forums = FollowsForum.objects.filter(user=client_user)

        followed_forums_post = []
        for forum in followed_forums:
            forum_posts = Post.objects.filter(forum=forum.forum)
            followed_forums_post += forum_posts
    request.session['user_type'] = user_type
    context = {
        'post_list': post_list,
        'product_list': product_list,
        'user': request.user,
        'is_seller': is_seller,
        'liked_posts': liked_posts,
        'followed_forums_post': followed_forums_post,
    }

    return render(request, 'sports24h/index.html', context)


@login_required(login_url=reverse_lazy('sports24h:login_user'))
def posts_index(request):
    post_list = Post.objects.order_by('-created_at')
    liked_posts = Post.objects.filter(likes__user=request.user)
    product_list = Product.objects.order_by('-created_at')
    is_seller = Seller.objects.filter(user=request.user).exists()
    context = {
        'post_list': post_list,
        'product_list': product_list,
        'user': request.user,
        'liked_posts': liked_posts,
        'is_seller': is_seller
    }
    return render(request, 'sports24h/posts_index.html', context)


@login_required(login_url=reverse_lazy('sports24h:login_user'))
def products_index(request):
    product_list = Product.objects.order_by('-created_at')
    is_seller = Seller.objects.filter(user=request.user).exists()
    context = {
        'product_list': product_list,
        'user': request.user,
        'is_seller': is_seller
    }
    return render(request, 'sports24h/products_index.html', context)


@user_passes_test(seller_check, login_url=reverse_lazy('sports24h:access_denied'))
@login_required(login_url=reverse_lazy('sports24h:login_user'))
def post(request):
    if not request.method == 'POST':
        forum_list = Forum.objects.order_by('-name')
        context = {
            'forum_list': forum_list,
        }
        return render(request, 'sports24h/create_post.html', context)
    title = request.POST.get('title', '')
    forum = request.POST.get('forum', '')
    text = request.POST.get('text', '')
    s = Seller.objects.get(user=request.user)
    if title and forum and text:
        f = Forum.objects.get(name=forum)
        p = Post(owner=s, forum=f, title=title, text=text)
        p.save()
    return HttpResponseRedirect(reverse('sports24h:index'))


@login_required(login_url=reverse_lazy('sports24h:login_user'))  # TODO permitir apenas seller ter acesso a esta view
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.owner.user == request.user:
        post.delete()
    return HttpResponseRedirect(reverse('sports24h:index'))


def client_check(user):
    return Client.objects.filter(user=user).exists()


def admin_check(user):
    return user.is_superuser or user.is_staff


def access_denied(request):
    return render(request, 'sports24h/accessdenied.html')


@user_passes_test(seller_check, login_url=reverse_lazy('sports24h:access_denied'))
@login_required(login_url=reverse_lazy('sports24h:login_user'))
def product(request):
    if not request.method == 'POST':
        forum_list = Forum.objects.order_by('-name')
        size_list = Size.objects.order_by('-name')
        context = {
            'forum_list': forum_list,
            'size_list': size_list
        }
        return render(request, 'sports24h/create_product.html', context)
    name = request.POST.get('name')
    size = request.POST.get('size')
    forum = request.POST.get('forum')
    price = request.POST.get('price')
    photo = request.FILES['photo']
    if name and size and photo and forum and price:
        seller = Seller.objects.get(user=request.user)
        s = Size.objects.get(name=size)
        f = Forum.objects.get(name=forum)
        p = Product.objects.create(owner=seller, name=name, size=s, photo=photo, price=price, forum=f)
        return HttpResponseRedirect(reverse('sports24h:index'))
    else:
        context = {
            'error_message': "Please, check if the fields are correctly filled.",
        }
        return render(request, 'sports24h/product.html', context)


@user_passes_test(seller_check)
@login_required(login_url=reverse_lazy('sports24h:login_user'))
def delete_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if product.owner.user == request.use:
        product.delete()
    return HttpResponseRedirect(reverse('sports24h:index'))


@login_required(login_url=reverse_lazy('sports24h:login_user'))
def follow_user(request):
    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        user = User.objects.get(id=user_id)
        follows, created = Follows.objects.get_or_create(following_user=request.user, followed_user=user)
        if created:
            follows.save()
            return redirect('sports24h:search_users')
        else:
            return redirect('sports24h:search_users')


@login_required(login_url=reverse_lazy('sports24h:login_user'))
def search_users(request):
    if not request.method == 'POST':
        followed_user_ids = Follows.objects.filter(
            following_user=request.user
        ).values_list('followed_user__id', flat=True)
        followed_users = User.objects.filter(
            id__in=followed_user_ids
        )
        context = {
            'followed_users': followed_users
        }

        return render(request, 'sports24h/search_users.html', context)
    search_query = request.POST.get('search_query')
    followed_user_ids = Follows.objects.filter(
        following_user=request.user
    ).values_list('followed_user__id', flat=True)

    # filter the search results to exclude followed users
    users = User.objects.filter(
        username__icontains=search_query
    ).exclude(
        id=request.user.id
    ).exclude(
        id__in=followed_user_ids
    )

    # get the list of User objects of the followed users
    followed_users = User.objects.filter(
        id__in=followed_user_ids
    )

    context = {
        'users': users,
        'followed_users': followed_users
    }
    return render(request, 'sports24h/search_users.html', context)


@login_required(login_url=reverse_lazy('sports24h:login_user'))
def unfollow_user(request):
    user_id = request.POST.get('user_id')
    followed_user = get_object_or_404(User, id=user_id)
    if user_id is not None:
        follow = Follows.objects.get(following_user=request.user, followed_user=followed_user)
        follow.delete()
    return redirect('sports24h:search_users')


@login_required(login_url=reverse_lazy('sports24h:login_user'))
def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    is_owner = Seller.objects.filter(user=request.user).exists()
    average_rating = Review.objects.filter(product=product).aggregate(Avg('rating'))['rating__avg']
    context = {
        'product': product,
        'is_owner': is_owner,
        'average_rating': average_rating
    }
    return render(request, 'sports24h/product_detail.html', context)


@login_required(login_url=reverse_lazy('sports24h:login_user'))
def post_detail(request, post_id):
    post = get_object_or_404(Post.objects.select_related('owner__user'), pk=post_id)
    comments = Comment.objects.filter(post=post)
    is_owner = Seller.objects.filter(user=request.user).exists()
    context = {
        'post': post,
        'comments': comments,
        'is_owner': is_owner
    }
    return render(request, 'sports24h/post_detail.html', context)


@login_required(login_url=reverse_lazy('sports24h:login_user'))
def add_comment(request):
    if request.method == 'POST':

sitediam/sports24h/templates/sports24h/create_post.html
{% extends "sports24h/create_product.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
	<title>Create Post</title>
	{% endblock %}
</head>
<body>
    {% block content %}
    <form id="post" class="post" action="{% url 'sports24h:create_post' %}" method="post">
        {% csrf_token %}
        <h2>Create new post</h2>
        <label>Title: </label>
        <input type="text" name="title" value="" >
        <label> Forum:</label>
        <select id="forums" name="forum">
            {% for forum in forum_list %}
            <option value="{{ forum.name }}">{{ forum.name }} - {{ forum.genre }}</option>
            {% endfor %}
        </select>
        <label> Description:</label>
        <input type="text" name="text" value="">
        <p></p>
    </form>
    {% endblock %}
	{% block error_messages %}
    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %}
	{% endblock %}

</body>
</html>

sitediam/sports24h/templates/sports24h/create_size.html
{% extends "sports24h/create_product.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
	<title>Create Size</title>
	{% endblock %}
</head>
<body>
    {% block content %}
    <form id="post" class="post" action="{% url 'sports24h:create_size' %}" method="post">
        {% csrf_token %}
        <h2>Create new size</h2>
        <label>Name: </label>
        <input type="text" name="name" value="" >
    </form>
    {% endblock %}
</body>
</html>

sitediam/sports24h/templates/sports24h/create_team.html
{% extends "sports24h/create_product.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>Create Team</title>
    {% endblock %}
</head>
<body>
  {% block content %}
    <form id="post" class="post" action="{% url 'sports24h:create_team' %}" method="post">
        {% csrf_token %}
        <h2>Create new team</h2>
        <label>Name: </label>
        <input type="text" name="name" value="" >
        <label> Country:</label>
        <select id="country" name="countries">
            {% for country in country_list %}
            <option value="{{ country.name }}">{{ country.name }}</option>
            {% endfor %}
        </select>
    </form>
    {% endblock %}
</body>
</html>

sitediam/sports24h/templates/sports24h/posts_index.html
{% extends "sports24h/index.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>Posts</title>
    {% endblock %}
</head>
<body>
    {% block content %}
    <script>
        function toggleCommentForm(postId) {
            console.log("Toggle comment form for post:", postId);
            const commentForm = document.getElementById("comment-form-" + postId);
            const commentButton = document.getElementById("button-add-comment-" + postId);

            commentForm.style.display = "block";
            commentButton.style.display = "none";
        }
    </script>
    <main>
        <section>
            {% if is_seller or request.user.is_superuser%}
                <div class="create_post">
                    <a href="{% url 'sports24h:create_post' %}">Create new Post</a>
                </div>
            {% endif %}
        </section>
        <section>
            <h2>Latest Posts</h2>
            {% for post in post_list %}
                <div class="post">
                    <a id="post" href="{% url 'sports24h:post_detail' post_id=post.id %}">
                        <h3>{{ post.title }} by {{ post.owner.user.username }}</h3>
                        <p>{{ post.text }}</p>
                    </a>
                    <div class="options">
                        <div class="add-comment">
                            <button type="button" id="button-add-comment-{{ post.id }}" onclick="toggleCommentForm('{{ post.id }}')">Comment</button>
                        </div>
                        <form method="post" action="{% url 'sports24h:add_comment' %}">
                            {% csrf_token %}
                            <div class="comment-form" id="comment-form-{{ post.id }}">
                                <input type="text" name="comment_text" placeholder="Enter your comment">
                                <input type="hidden" name="post_id" value="{{ post.id }}">
                                <button type="submit">Add Comment</button>
                            </div>
                        </form>
                        <a href="{% url 'sports24h:like' post_id=post.id %}">
                            {% if post in liked_posts %}
                                Dislike {{ post.likes_count }}
                            {% else %}
                                Like {{ post.likes_count }}
                            {% endif %}
                        </a>
                    </div>
                </div>
            {% endfor %}
            <!-- more user-generated posts -->
        </section>
    </main>
    {% endblock %}

</body>
</html>

sitediam/sports24h/templates/sports24h/product_detail.html
<!DOCTYPE html>
{% extends "sports24h/index.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Product Detail {{ product.id }}</title>
    <style>
        .add-to-cart {
            display: inline-block;
            padding: 10px;
            border: 1px solid #ccc;
            text-decoration: none;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
        }
    </style>
</head>
    <body>
        {% block content %}
        <div class="product">
            <h2>{{ product.name }}</h2>
            <p>Size: {{ product.size.name }}</p>
            <p>Forum: {{ product.forum.name }}</p>
            <p>Price: {{ product.price }}</p>
            <img src="{{ product.photo.url }}" alt="Profile Photo" class="dropdown-trigger">
            <p>Average rating = {{ average_rating }}</p>
            <a href="{% url 'sports24h:add_to_cart' product_id=product.id %}" class="add-to-cart">Add to cart</a>
            {% if is_owner %}
            <input type="submit" value="Delete" onclick="window.location.href='{% url 'sports24h:delete_product' %}'" />
            {% endif %}
        </div>
        {% endblock %}
    </body>
</html>

sitediam/sports24h/templates/sports24h/profile.html
{% extends "sports24h/index.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile</title>
</head>
<body>
{% block content %}

<div class="profile">
    <p>Username: {{ request.user.username }}</p>
    <p>Email: {{ request.user.email }}</p>
    <p>Date of Registration: {{ request.user.date_joined }}</p>
    <p>Number Of Followers: {{ nr_followers }}</p>
    <img src="{{ request.session.photo }}" alt="Profile Photo" class="dropdown-trigger">

    <div class="side-by-side">
        {% if c.country.name %}
        <!-- Display the current country -->
        <p>Country: {{ c.country.name }}</p>
        <form method="post" action="{% url 'sports24h:set_country' %}">
            {% csrf_token %}
            <button type="button" class="addToProfile" onclick="showInputCountry()">Change Country</button>
            <div class="country-input" style="display: none;">
                <select name="country">
                    {% for country in countries %}
                    <option value="{{ country.name }}">{{ country.name }}</option>
                    {% endfor %}
                </select>
                <button type="submit">Save</button>
            </div>
        </form>
        {% else %}
        <!-- No country selected -->
        <form method="post" action="{% url 'sports24h:set_country' %}">
            {% csrf_token %}
            <button type="button" class="addToProfile" onclick="showInputCountry()">Add Country</button>
            <div class="country-input" style="display: none;">
                <select name="country">
                    {% for country in countries %}
                    <option value="{{ country.name }}">{{ country.name }}</option>
                    {% endfor %}
                </select>
                <button type="submit">Save</button>
            </div>
        </form>
        {% endif %}
        <script>
            function showInputCountry() {
                document.getElementsByClassName("country-input")[0].style.display = "block";
            }
        </script>
        {% if c.favorite_team %}
<!-- Display the current favorite team -->
<p>Favorite Team: {{ c.favorite_team.name }}</p>
<p>Favorite Team Country: {{ c.favorite_team.country.name }}</p>
<form method="post" action="{% url 'sports24h:set_favoriteTeam' %}">
    {% csrf_token %}
    <button type="button" class="addToProfile" onclick="showInputFavoriteTeam()">Change Favorite Team</button>
    <div class="favorite_team-input" style="display: none;">
        <label for="teamCountry">Team Country:</label>
        <select name="teamCountry" id="teamCountry2">
            {% for team in teams %}
            <option value="{{ team.country.name }}" >{{ team.country.name }}</option>
            {% endfor %}
        </select>
        <label for="teamName">Team Name:</label>
        <select name="teamName" id="teamName2">
            {% for team in teams %}
            <option value="{{ team.name }}" >{{ team.name }}</option>
            {% endfor %}
        </select>
        <button type="submit">Save</button>
    </div>
</form>
{% else %}
<!-- No favorite team selected -->
<form method="post" action="{% url 'sports24h:set_favoriteTeam' %}">
    {% csrf_token %}
    <button type="button" class="addToProfile" onclick="showInputFavoriteTeam()">Add Favorite Team</button>
    <div class="favorite_team-input" style="display: none;">
        <label for="teamCountry">Team Country:</label>
        <select name="teamCountry" id="teamCountry">
            {% for team in teams %}
            <option value="{{ team.country.name }}">{{ team.country.name }}</option>
            {% endfor %}
        </select>
        <label for="teamName">Team Name:</label>
        <select name="teamName" id="teamName">
            {% for team in teams %}
            <option value="{{ team.name }}">{{ team.name }}</option>l
            {% endfor %}
        </select>
        <button type="submit">Save</button>
    </div>
</form>
{% endif %}
        <script>
            function showInputFavoriteTeam() {
                document.getElementsByClassName("favorite_team-input")[0].style.display = "block";
            }
        </script>
{% if c.favorite_sport %}
<p>Favorite Sport: {{ c.favorite_sport.name }}</p>
<form method="post" action="{% url 'sports24h:set_favoriteSport' %}">
    {% csrf_token %}
    <button type="button" class="addToProfile" onclick="showInputFavoriteSport()">Change Favorite Sport</button>
    <div class="favorite_sport-input" style="display: none;">
        <select name="sportName">
            {% for sport in sports %}
            <option value="{{ sport.name }}" {% if sport.name == c.favorite_sport.name %}selected{% endif %}>{{ sport.name }}</option>
            {% endfor %}
        </select>
        <button type="submit">Save</button>
    </div>
</form>
{% else %}
<!-- No favorite sport selected -->
<form method="post" action="{% url 'sports24h:set_favoriteSport' %}">
    {% csrf_token %}
    <button type="button" class="addToProfile" onclick="showInputFavoriteSport()">Add Favorite Sport</button>
    <div class="favorite_sport-input" style="display: none;">
        <select name="sportName">
            {% for sport in sports %}
            <option value="{{ sport.name }}">{{ sport.name }}</option>
            {% endfor %}
        </select>
        <button type="submit">Save</button>
    </div>
</form>
{% endif %}

<script>
    function showInputFavoriteSport() {
        document.getElementsByClassName("favorite_sport-input")[0].style.display = "block";
    }
</script>


    </div>
    <p><strong>{{ set_profile_setting }}</strong></p>

    <form id="upload" method="post" enctype="multipart/form-data"  action="{% url 'sports24h:upload_photo' %}">
        {% csrf_token %}
<div class="file_upload_container">
    <input type="file" id="file" class="get_file" name="myfile">
    <label for="file" class="file_label">Choose file</label>
</div>
        <p></p>
    </form>
    <form id="reset" action="{% url 'sports24h:reset_photo' %}">
    {% csrf_token %}
    <p></p>
</form>
{% if uploaded_file_status %}
<p><strong>{{ uploaded_file_status }}</strong></p>
{% endif %}
{% endblock %}

{% block options_and_controls %}
<div class="options-and-controls">
    <input type="submit" value="Update photo" form="upload" class="button">
    <p></p>
    <input type="submit" value="Remove photo" form="reset" class="button">
    <p></p>
    <form action="{% url 'sports24h:delete_account' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete Account" class="button">
    </form>
</div>
{% endblock %}

{% block error_messages %}
{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}
{% endblock %}
</div>
</body>
</html>

sitediam/sports24h/templates/sports24h/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>Register</title>
    {% endblock %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'sports24h/styles.css' %}" />
    <style>
        .required {
            color: red;
        }
    </style>
</head>
<body>
{% block header %}
    <header>
        <div class="top">
            <h1>Sports24h</h1>
        {% csrf_token %}
        </div>
    </header>
{% endblock %}
    {% block content %}
    <form id="register" action="{% url 'sports24h:register_user' %}" method="post">
        {% csrf_token %}
        <h1>Introduza os seus dados para registo de utilizador: </h1>
        <label for="user-type">Register as:</label>
        <div id="user-type">
            <input type="radio" name="user_type" value="client" id="client" checked>
            <label for="client">Client</label>
            <input type="radio" name="user_type" value="seller" id="seller">
            <label for="seller">Seller</label>
        </div>
        <label> Username<span class="required">*</span>: </label>
            <input type="text" name="username" value="" >
        <label> E-mail<span class="required">*</span>: </label>
            <input type="email" name="email" value="" >
        <label> Password<span class="required">*</span>:</label>
            <input type="password" name="password" value="" >
        <label> Confirm Password<span class="required">*</span>:</label>
            <input type="password" name="confirm_password" value="" >
        <label> Birthdate<span class="required">*</span>:</label>
            <input type="date" name="birthdate" value="" >
        {% csrf_token %}
    </form>
    <form id="upload" method="post" enctype="multipart/form-data"  action="{% url 'sports24h:upload_photo' %}">
        {% csrf_token %}

        <input type="file" name="myfile">
        <p></p>
    </form>
    <input type="submit" value="Submeter foto" form="upload">

    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    {% endblock %}
    {% block options_and_controls %}
    <input type="submit" value="Register" form="register"/>
    {% endblock %}
</body>
</html>

sitediam/sports24h/templates/sports24h/search_users.html
<!DOCTYPE html>
{% extends "sports24h/index.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>Follow</title>
    {% endblock %}
    <style>

    </style>
</head>
<body>
<main>
    {% block content %}
    <h1 class="search-title">Search Users</h1>
    {% if message %}
    {{ message }}
    {% endif %}
    <form id="search-form" method="POST">
        {% csrf_token %}
        <div class="search-container">
          <input type="text" name="search_query" id="search-query" placeholder="Search users">
          <button type="submit"><i class="fa fa-search">Search</i></button>
        </div>
    </form>
    <div class="search-results">
        {% for user in users %}
<form method="POST" action="{% url 'sports24h:follow_user' %}">
            {% csrf_token %}
            <div class="search-result">
              <input type="hidden" name="user_id" value="{{ user.id }}">
                <a href="{% url 'sports24h:other_user_profile' user_id=user.id %}" class="username-anchor">
              <p>{{ user.username }}
                  <button type="submit">Follow</button>
</p></a>
            </div>
</form>
        {% endfor %}
    </div>
    <h3>Followed users</h3>
    <div id="followed users">
        {% if followed_users %}
        {% for user in followed_users %}
        <form method="POST" action="{% url 'sports24h:unfollow_user' %}">
            {% csrf_token %}
            <div class="search-result">
              <input type="hidden" name="user_id" value="{{ user.id }}">
                <a href="{% url 'sports24h:other_user_profile' user_id=user.id %}" class="username-anchor">
              <p>{{ user.username }}
                  <button type="submit">Unfollow</button>
              </p></a>
            </div>
        </form>
        {% endfor %}
        {% else %}
        <div class="alert alert-info">You are not following anyone yet.</div>
        {% endif %}
    </div>
    {% endblock %}
</main>
</body>
</html>